#' Get the Varieties for Each combination of OCF and RCF Scales
#'
#' @param OCF_df A data frame generated by the OCF function
#' @param RCF_df A data frame generated by the RCF function
#' @param quantiles Which quantiles you want to break the RCf and OCF distributions
#' @param type Normal scale or Logarithm scale. Default value is log scale.
#'
#' @returns A tibble with a column called varieties which have the list of varieties for each combination of scales.
#' @export
#'
#' @examples
#' data(varieties_data)
#' ocf_data <- OCF(dfr=varieties_data,
#' vname="variety_name",
#' hh="household_code",
#' community="community",
#' location="location")
#' rcf_data <- RCF(dfr=varieties_data,
#' vname="variety_name",
#' hh="household_code",
#' nsvarie="number_of_tubers",
#' community="community",
#' location="location")
#' combined_scales <- Get_Red_Listing(ocf_data, rcf_data)
#' red_listing_varieties <- combined_scales$varieties[[1]]
#' print(red_listing_varieties)
Get_Red_Listing <- function(OCF_df,
                            RCF_df,
                            quantiles = c(0.25, 0.5, 0.75),
                            type = "log") {
    if (type == "normal") {
        quantiles_OCF <- OCF_df %>%
            dplyr::summarize(
                Q1_ocf = quantile(OCF, probs = quantiles[1], na.rm = TRUE),
                Median_ocf = quantile(OCF, probs = quantiles[2], na.rm = TRUE),
                Q3_ocf = quantile(OCF, probs = quantiles[3], na.rm = TRUE),
                .groups = "drop"
            )

        quantiles_RCF <- RCF_df %>%
            dplyr::summarize(
                Q1_rcf = quantile(RCF, probs = quantiles[1], na.rm = TRUE),
                Median_rcf = quantile(RCF, probs = quantiles[2], na.rm = TRUE),
                Q3_rcf = quantile(RCF, probs = quantiles[3], na.rm = TRUE),
                .groups = "drop"
            )

        joined_df <- RCF_df %>%
            dplyr::left_join(OCF_df, by = dplyr::join_by(variety_name, community))

        joined_df <- joined_df %>%
            dplyr::mutate(
                OCF_scale = dplyr::case_when(
                    OCF < quantiles_OCF[1][[1]] ~ "very few households",
                    OCF >= quantiles_OCF[1][[1]] &
                        OCF < quantiles_OCF[2][[1]] ~ "few households",
                    OCF >= quantiles_OCF[2][[1]] &
                        OCF < quantiles_OCF[3][[1]] ~ "many households",
                    OCF >= quantiles_OCF[3][[1]] ~ "most households",
                )
            ) %>%
            dplyr::mutate(OCF_scale = factor(
                OCF_scale,
                levels = c(
                    "very few households",
                    "few households",
                    "many households",
                    "most households"
                )
            )) %>%
            dplyr::mutate(
                RCF_scale = dplyr::case_when(
                    RCF < quantiles_RCF[1][[1]] ~ "very scarse",
                    RCF >= quantiles_RCF[1][[1]] &
                        RCF < quantiles_RCF[2][[1]] ~ "scarse",
                    RCF >= quantiles_RCF[2][[1]] &
                        RCF < quantiles_RCF[3][[1]] ~ "common",
                    RCF >= quantiles_RCF[3][[1]] ~ "abundant",
                )
            ) %>%
            dplyr::mutate(RCF_scale = factor(
                RCF_scale,
                levels = c("very scarse", "scarse", "common", "abundant")
            ))

        # Grouping and summarizing to get varieties as a list in each combination of OCF and RCF scales
        variety_combinations <- joined_df %>%
            dplyr::group_by(OCF_scale, RCF_scale) %>%
            dplyr::summarize(varieties = list(unique(variety_name)), .groups = "drop")

        # Display the resulting dataframe
        return(variety_combinations)



    } else if (type == "log") {
        quantiles_OCF <- OCF_df %>%
            dplyr::summarize(
                Q1_ocf = quantile(log(OCF), probs = quantiles[1], na.rm = TRUE),
                Median_ocf = quantile(log(OCF), probs = quantiles[2], na.rm = TRUE),
                Q3_ocf = quantile(log(OCF), probs = quantiles[3], na.rm = TRUE),
                .groups = "drop"
            )

        quantiles_RCF <- RCF_df %>%
            dplyr::summarize(
                Q1_rcf = quantile(log(RCF), probs = quantiles[1], na.rm = TRUE),
                Median_rcf = quantile(log(RCF), probs = quantiles[2], na.rm = TRUE),
                Q3_rcf = quantile(log(RCF), probs = quantiles[3], na.rm = TRUE),
                .groups = "drop"
            )


        joined_df <- RCF_df %>%
            dplyr::left_join(OCF_df, by = dplyr::join_by(variety_name, community))

        joined_df <- joined_df %>%
            dplyr::mutate(
                OCF_scale = dplyr::case_when(
                    log(OCF) < quantiles_OCF[1][[1]] ~ "very few households",
                    log(OCF) >= quantiles_OCF[1][[1]] &
                        log(OCF) < quantiles_OCF[2][[1]] ~ "few households",
                    log(OCF) >= quantiles_OCF[2][[1]] &
                        log(OCF) < quantiles_OCF[3][[1]] ~ "many households",
                    log(OCF) >= quantiles_OCF[3][[1]] ~ "most households",
                )
            ) %>%
            dplyr::mutate(OCF_scale = factor(
                OCF_scale,
                levels = c(
                    "very few households",
                    "few households",
                    "many households",
                    "most households"
                )
            )) %>%
            dplyr::mutate(
                RCF_scale = dplyr::case_when(
                    log(RCF) < quantiles_RCF[1][[1]] ~ "very scarse",
                    log(RCF) >= quantiles_RCF[1][[1]] &
                        log(RCF) < quantiles_RCF[2][[1]] ~ "scarse",
                    log(RCF) >= quantiles_RCF[2][[1]] &
                        log(RCF) < quantiles_RCF[3][[1]] ~ "common",
                    log(RCF) >= quantiles_RCF[3][[1]] ~ "abundant",
                )
            ) %>%
            dplyr::mutate(RCF_scale = factor(
                RCF_scale,
                levels = c("very scarse", "scarse", "common", "abundant")
            ))

        # Grouping and summarizing to get varieties as a list in each combination of OCF and RCF scales
        variety_combinations <- joined_df %>%
            dplyr::group_by(OCF_scale, RCF_scale) %>%
            dplyr::summarize(varieties = list(unique(variety_name)), .groups = "drop")

        # Display the resulting dataframe
        return(variety_combinations)


    }

}

community <- OCF_scale <- RCF_scale <- NULL
